utils::globalVariables(c("VEC_ID","FOL_ID","IDE_EDA_ANO", "IDE_SEX",
                         "DES_CAL","IDE_CAL", "NUM_EXT", "NUM_INT",
                         "IDE_COL", "IDE_CP",
                         "CVE_LOC_RES", "DES_LOC_RES", "CVE_MPO_RES", "DES_MPO_RES",
                         "DES_JUR_RES",
                         "CVE_EDO_RES", "DES_EDO_RES",
                         "CVE_EDO_REP", "DES_EDO_REP",
                         "CVE_LOC_REP", "DES_LOC_REP",
                         "CVE_MPO_REP", "DES_MPO_REP",
                         "ESTATUS_CASO", "CVE_DIAG_PROBABLE", "DES_DIAG_PROBABLE", "DES_DIAG_FINAL",
                         "FEC_INI_SIGNOS_SINT", "ANO", "SEM",
                         "MANEJO",
                         "DES_INS_UNIDAD",
                         "DENGUE_SER_TRIPLEX",
                         "FEC_INGRESO"))
