utils::globalVariables(c("VEC_ID","FOL_ID","IDE_EDA_ANO", "IDE_SEX",
                         "DES_CAL","IDE_CAL", "NUM_EXT", "NUM_INT",
                         "IDE_COL", "IDE_CP",
                         "CVE_LOC_RES", "DES_LOC_RES", "CVE_MPO_RES", "DES_MPO_RES",
                         "DES_JUR_RES",
                         "CVE_EDO_RES", "DES_EDO_RES",
                         "CVE_EDO_REP", "DES_EDO_REP",
                         "CVE_LOC_REP", "DES_LOC_REP",
                         "CVE_MPO_REP", "DES_MPO_REP",
                         "ESTATUS_CASO", "CVE_DIAG_PROBABLE", "DES_DIAG_PROBABLE", "DES_DIAG_FINAL",
                         "FEC_INI_SIGNOS_SINT", "ANO", "SEM",
                         "MANEJO",
                         "DES_INS_UNIDAD",
                         "DENGUE_SER_TRIPLEX",
                         "FEC_INGRESO", "CVE_ENT", "week",
                         "n", "1","2", "3", "Porcentaje_Positividad",
                         "estimados", "sector", "manzana", "Localidad",
                         "sec_manz", "eggs", "ovitrap", "n_ovitraps_positive",
                         "n_ovitraps_negative", "n_ovitraps_lectura",
                         "n_ovitraps_install", "n_block_positive",
                         "n_blocks", "sum_ovitrap_positive",
                         "locality", "avg_HOP", "avg_HMP",
                         "perc_OP", "perc_MP", "perc_lectura",
                         "accuracy", "long", "lat", "x", "y",
                         "level", "entidad", "layer", "D1",
                         "D2", "D3", "D4",
                         "D1_binary", "D2_binary", "D3_binary",
                         "D4_binary",
                         "D1_text", "D2_text", "D3_text", "D4_text",
                         "n_serotipo", "serotype_combination",
                         "value", "kernel",
                         "status_caso", "estatus_caso"))
